# Generated by Django 3.0.5 on 2020-05-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
