# Generated by Django 3.0.5 on 2020-05-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='score',
            new_name='avg_score',
        ),
        migrations.AlterField(
            model_name='place',
            name='external_source',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
